# Generated by Django 2.2.6 on 2020-04-08 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_author_authordetail_book_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publish',
            name='address',
            field=models.CharField(max_length=64),
        ),
    ]
