# Generated by Django 2.2.6 on 2020-04-07 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('pwd', models.CharField(max_length=32)),
                ('phone', models.CharField(max_length=32)),
                ('sex', models.IntegerField(choices=[(1, '男'), (2, '女')])),
                ('icon', models.ImageField(default='icon/2.jpg', upload_to='icon')),
            ],
            options={
                'verbose_name': '信息',
                'verbose_name_plural': '信息',
                'db_table': 'usersex',
            },
        ),
    ]
